---
title: Good Morning, Soda
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: roguescholar42@gmail.com
description: 'Morning toughts. Also soda. '
baseurl: ''
url: https://roguescholar42.github.io
twitter_username: roguescholar42
github_username: roguescholar42
theme: jekyll-whiteglass
plugins:
- jekyll-feed
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
permalink: "/:year/:month/:day/:title/"
paginate_path: "/posts/:num/"
paginate: 10
